# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69bf5f2d3616aaced28af39c06da292e83d258c92ebf26e14952467edfa72214496b4f10fd1d21bfcd50751c5420d4f0d999a73ffda27a7839e27f86486c3b9a

test:
  secret_key_base: c7027a416dc6a6e136b741db1bfbb9578392412c58e9b127eb84678d7671cfde8d8565246397b4cd95aa3b0da0fc0da19d74f6a5c8925681880a00d401685f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
